#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/mman.h>
#include <string.h>
int main ()
{
  printf (" WWWWWWWWWWWWWWWWNX0koc,..   .,;,'.'''':::locoKNWWWWWWWWWWWWWWWWWWWWWWW\n MMMMMMMMMMMWMMWKl,'..                      ..'oOKNWWWWMMMMMMMMMMMMMMMM\n MMMMMMMMMMWXOo:'.           ....................,lONWMMMMMMMMMMMMMMMMM\n MMMMMMMMW0o'.  ..............',,,,,;;;;,,,,,,,,,'',cdOXWMMMMMMMMMMMMMM\n MMMMMMNOc......''''',,',,,,,;;::;;;:::;;;;;;,,,,,''''':d0NMMMMMMMMMMMM\n MMMMW0c...',,,;;;;:::::::::::::::::::::;;;;;;,,,,,,,,,,',oKWMMMMMMMMMM\n MMMWk'.',;;::::cclllcccclcccccccccccc:::;;;;;,,,,,,,,,''''lKWMMMMMMMMM\n MMWx'.,;::cclllloooooooooooolllllllllccc:::;;;;;;;,,,''....lXWMMMMMMMM\n MWO;';:cclloooooddddxxxxxxxxxxddooollllccccc::;;,,'...... ..oXMMMMMMMM\n WNo';::ccllooodxxxkkOOO000OOOkkxxddooollcccccc:;;,,'...   ...xWMMMMMMM\n M0c;::ccllloodkkOOOO0000000OOkkxxddooooooolllllc:;,.........,OWMMMMMMM\n Wk:::ccccllodxkO0000000000OOOkkxxdddddddoooolc:;;,'..  ....'xNMMMMMMMM\n Wx:c:cccccllodkOO0000000OOOkkxxddddoooollcc:;,'''...   ....;kXWWWWMMMM\n Nd:c:ccccccllodxkkkOOkkkkkkxxdddddooollcc::;;,'''...  ...',;coxkO0KKXN\n Xo:::ccccccclllllodxkkkkkxxxxdddddoooollccc:::;;,'......',;::ccllooood\n Xo:::cccccllcc::::cldxkxxxxxxxxxxxxxxdddolllcccc::;,''''',;clloolc:cll\n Xd:::ccclll:;cc;:clodxkxxxkOO0O00O0K0kkOkxxolllllllc:;,,'.;looc;,',:oO\n Wkc::::ccll,:oc;',looxkxxxkKKKK0K00X0kkOkxkdooooooolc:;'..';:;;,'',oKW\n MNd:::;::cl:cl,..:llldxxxxkkkkkkOOO0OkOOOkkxdddooollc:,...,::;;,...;0W\n MMXd:;;;::ccll:,cooddoxkkkkkkkOOkkkkkOOOOOkxxxdooollc;'.';:c:;;,....:K\n MMMKl;;;::cccldodkkOOxkkO0O000K0000000OOOOxxxkxxkxol:,'',cllooooooc,lK\n MMWW0l;;;::ccldddxxO000ddkO0000000KXK0OOOkxdoddxOkxo:,'':xO0000Okddd0W\n MMWWW0c;;;;:ccoddddddkd;:odxxkkOOO000OOOxdoc:cdxkxdl:,.'cddddddoollcoK\n MMMMMWOc,;;,,;:odxkxddollloodxxkkOOOOOOkxdollldxxdlc;;,;clc;;::ccc;,,d\n MMMMMMWk:,'....,cdxxddddollloodxxxkkkkxxxdoooooollc::;;:c;...........d\n MMMMMMMXl..';;,..cdddddoolc::clooddddddoooolllcccccc::::,...'''..  .oX\n MMMMMMM0;'l::kl'..cdoooollc:;;::cclllllllcccccccccccccc:...co;od'..lXM\n MMMMMMWd.,odlc,,,.'ldoollcc:;;,,;;;:::::::::::cccccllll;..,:oodo;..dWM\n MMMMMMX:.,,loodxl..;oollcc::;;,,,'''',,,,;;:::cccccllll;.':codddo,.oWM\n MMMMMMX:'dkoooc;,..,olc::;,,',,,,,''''...'',,;;;;::::cc,.'oxoooxx;'xWW\n MMMMMMXc,ollodo;;...,'.............................''''..',;ldo:l;;0MW\n MMMMMMWd'clcc;okc.    ..;c:cccccccccccc::;;;;;,,,'''......cdo::dx;:XMM\n MMMMMNO:.'odlldo'                ...................     .,olcod:.lXWM\n MMMMWx.   'cxOo'                                          .'lxd;...cKM\n");
}
